name: mon_application
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: bwnyasse <risbonyasse@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  markdown: ^2.0.3

dev_dependencies:
  mockito: ^4.1.1
  pedantic: ^1.7.0
  test: ^1.5.0
  build_cli: ^1.3.4
  build_cli_annotations: ^1.1.0
  build_runner: ^1.0.0

